WebClientAddress: http://localhost:8080

Db:
  Port: 5432
  Host: postgres
  Password: insecure
  Database: binaryx
  User: binaryx

Auth:
  Secret: 69cq25vwpbykesj9qg6tc8bkwuqpnm38
  Encoder: sn8rtqWLDMMdCqAajHVrGDNw5aiqYFUguM2tPv9JfJj2L5QdNSgXHDVTANU5VGfS
  ExpireTime: 24h

Email:
  Port: 587